# Generated by Django 5.0.6 on 2024-05-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friends',
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
