# Generated by Django 5.0.6 on 2024-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_friend_friends_rename_group_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='user_games', to='core.games'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_tags', to='core.tags'),
        ),
    ]
