# Generated by Django 5.0.6 on 2024-05-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_games_alter_user_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='name',
        ),
    ]
