# Generated by Django 5.0.6 on 2024-05-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tag_name_tags_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_name',
            new_name='name',
        ),
    ]
